apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-login-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: user-login.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-login-app
            port:
              number: 80